project:
  type: website
  output-dir: docs

website:
  title: "Thomas Leo Scherer"
  site-url: "https://www.tlscherer.com"  
  navbar:
    background: '#B31B1B'  # You can change the background color here
    left:
      - text: AbroadReview
        href: https://www.AbroadReview.com
      - text: Foreign Policy
        href: foreignpolicy.qmd
      - text: Gaming
        href: gaming.qmd
      - text: More
        menu:
        - text: About
          href: about.qmd
        - text: Publications
          href: publications.qmd
      # - text: Gaming
      #   menu:
      #   - text: Board Games
      #     href: posts.qmd#category=board_games
      #   - text: TTRPGs
      #     href: posts.qmd#category=TTRPGs
      #   - text: Computer Games
      #     href: posts.qmd#category=computer_games
    right:
      - text: "<span class='open-subscribe-modal' style='background-color: #0d6efd; color: white; padding: 4px 10px; border-radius: 4px; font-weight: 600; font-size: 0.85rem; cursor: pointer;'>Subscribe</span>"
        href: "javascript:void(0);"
      - text: "<span style='background-color: #1185fe; color: white; padding: 4px 6px; border-radius: 4px; display: inline-flex; align-items: center;'>{{< fa brands bluesky >}}</span>"
        href: https://bsky.app/profile/tlscherer.bsky.social
        target: _blank
      - text: "<span style='background-color: #0A66C2; color: white; padding: 4px 6px; border-radius: 4px; display: inline-flex; align-items: center;'>{{< fa brands linkedin >}}</span>"
        href: https://www.linkedin.com/in/thomas-scherer-b468847/
        target: _blank


  # google-analytics:
  #   tracking-id: ""  # Please delete or replace with your own tracking ID
  #   anonymize-ip: true 

  page-footer: 
    left: "Thomas Leo Scherer &copy; <script>document.write(new Date().getFullYear())</script>" 

format:
  html:
    theme:
      - cosmo
      - brand
    include-after-body: subscribe.html
    css: styles.css
    toc: true
    footnotes-hover: true
    # code-copy: true
    # code-link: true
    # code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    # link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    # include-in-header: "files/includes/_academic.qmd"
    header-includes: |
            <script async src="https://plausible.io/js/pa--CWv1kp2iawYibWYwQ4yq.js"></script>
      <script>
        window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)},plausible.init=plausible.init||function(i){plausible.o=i||{}};
        plausible.init()
